### ISSUE TITLE
Handle multiple client instances as unique participants

### ISSUE THREAD

**Issue by zimoony** [process-engine/skeleton#19]
#### Describe your issue

The skeleton test project process-engine-browser need to support the execution of multiple instances in the browser based on the participant who starts a process. E.g. when routing is performed on a server instance and the next task is a UserTask which needs a browser then the task should not be rendered on all client instances listening on the messagebus.

#### Possible solution

With the participantId this should be accomplished. At the moment an individual participant channel is created for each process instance <-> client instance relation in order to communicate only between the two and forward user task infos for rendering. Through this channel also boundary events are communicated.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
ok, this is what is supposed to happen, and what needs to be tested. We have the following scenario:

- We have charon open, connected to a node-process-engine-instance
- We have the aforementioned node-process-engine-instance running
- We have multiple browser-process-engine-instances running, all with the same Name and connected to the same node-process-engine-instance

We now have a process with multiple userTasks, probably on different lanes, and the following should happen delegation-wise

- charon starts the process
- the node-process-engine-instance delegates the execution to one of the browser-proces-engine-instances (because of feature-matching)
- the browser-process-engine-instance encounters a user-task
- a user takes that task, and assignes a participantId to that processInstance
- when the user proceeds the userTask, the process-execution should continue on the same browser-instance that last executed the process (the one that encountered the userTask)
- the browser-process-engine-instance continues the porcess-execution, delegating it back to the node-process-engine-instance (because of feature-matching)
- the node-process-engine-instance encounters another userTask
- the task is sent (via messagbus) to the same user that took the first userTask (using the participantId) if that user has the necessary rights
  - If the user is not available, for example when he logged off, the task just stays in the taskList
  - As soon as another user takes the task, he assignes that processInstance a new participant Id. This way a user can refresh the charon-tab, take the user-task again and continue as if he hadn't refreshed

An image of the test-process follows as soon as i have that test-process

**Comment by heikomat** [comment]
This is the process i use:

![bildschirmfoto 2017-11-13 um 14 17 05](https://user-images.githubusercontent.com/20770029/32727621-68d8614c-c87d-11e7-96e6-25e03552054c.png)

**Comment by heikomat** [comment]
distinguishing between multiple browser-process-engine-instances is currently not possible, because all browser-proces-engine-instances have the same applicationId as set in the application-service-config. Because of this i cannot currently fix the delegation to a single browser-process-engine-instance. For this to work, we need to implement our distributed-system-concept as described [here](https://docs.google.com/document/d/1B7zbJqybSLHnUz2jTTJRbKZxoymg8va8NlxUoa6HARw/edit#heading=h.dt2kx25pftz).

Because of this i'll continue testing with a single browser-process-engine-instance, and see if the participantId-system for the userTasks works
